cache:
  paths:
    - node_modules/

stages:
  - production build

deploy to production server:
  stage: production build
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/studikasus.git
    - git push heroku main:u
    - echo "Deployed to development server"
  only:
    - main
