stages:
  - test
  - dev build

# test aplication:
#   stage: test
#   image: node:17
#   script:
#     - yarn install
#     - yarn test
#   only:
#     - main
deploy to development server:
  image: node:17
  stage: dev build
  script:
    - yarn install
    - yarn test
  only:
    - main
