stages:
  - test
  - dev build

test aplication:
  image: node:lastest
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - main
deploy to development server:
  image: node:latest
  stage: dev build
  script:
    - npm install
    - npm run test
  only:
    - main
