cache:
  paths:
    - node_modules/

stages:
  - production build

deploy to production server:
  stage: production build
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
