stages:
  - test
  - dev build

test aplication:
  stage: test
  # image: node:6.9.0
  script:
    - yarn install
    - yarn test
  only:
    - main
# deploy to development server:
#   image: node:6.9.0
#   stage: dev build
#   script:
#     - yarn install
#     - yarn test
#   only:
#     - main
