cache:
  paths:
    - node_modules/

stages:
  - test
  - development build
  - production build

test application:
  image: node:17
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - main
