
export const products = [
  {
    id :1,
    name : "Nike AJ 12 retro",
    img:'/sepatu.png',
    rating: 4.5,
    price: 10000000,
    discount: 10,
    brand: "nike",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#749F82",
    tag: 'new',
    desc: "Available 7/24 at 10:00 AM The OG Air Jordan 12 was a first for Jordan Brand, even if what MJ did wearing them wasn't a first for him. Lacing up in the first official Jordan Brand model throughout the 1996 - 97 season, MJ won another title in the Air Jordan 12, often rocking the OG Cherry colourway. Nearly 25 years later, the beloved Cherry is receiving a classic twist with this new Air Jordan 12 colourway. Instead of University Red dominating the makeup of the outside upper, midsole and sole, the Red Metallic colourway reverses the Cherry original, with a clean white leather covering the upper instead. To top it all off, University Red accents on the midfoot and eyestays complete the full twist.",
    review: [
      {
        idUser: 1,
        userName: "John",
        comment: "product very nice"
      },
      {
        idUser: 2,
        userName: "doe",
        comment: "product very nice"
      },
    ]
  },
  {
    id :2,
    name : "Addidas Supernova ",
    img:'/sepatu.png',
    rating: 4,
    price: 100000,
    discount: 20,
    brand: "addidas",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#749F82",
    tag: 'new',
    desc: 'a supernova is the explosion of a star in space. It happens when a star has reached the end of its life and dies in a brilliant explosion — the biggest explosion that humans have ever seen. Since most stars can live for billions of years, it’s perhaps not surprising that when adidas launched their new running model in 2013 after 30 years of research, testing and reviewing, they dubbed it the Supernova because it was built for long-distance running and comfort.'

  },
  {
    id :3,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 5,
    price: 100000,
    discount: 50,
    brand: "reebok",
    colorA: "#000",
    colorB: "#628E90",
    colorC: "#749F82",
    desc: 'The Reebok NanoFlex TR is a type of training shoe designed for athletes and fitness enthusiasts. The shoe features a flexible and breathable upper made of synthetic materials and mesh, which allows for ventilation and flexibility during exercise. The shoe also has a low-cut design to enhance ankle mobility and a midsole cushioning system for shock absorption during high-impact movements.The outsole of the NanoFlex TR is made of a durable rubber material with a multidirectional tread pattern, providing excellent traction on a variety of surfaces. Additionally, the shoe includes a 360-degree TPU heel wrap for added stability during lateral movements, such as agility drills and side lunges.Overall, the Reebok NanoFlex TR is a versatile and durable training shoe suitable for a range of exercises, including weightlifting, CrossFit, and HIIT workouts.'
  },
  {
    id :4,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    discount: 20,
    brand: "reebok",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#628E90",
    desc:'CMEVA Midsole Cushioning for long lasting comfort, Comfort Footbed 5MM OPEN CELL FOAM WITH LESS THAN 5 Percent COMPRESSION SET OVER TIME, SO THE CUSHIONING AND FIT NEVER CHANGES INSIDE THE SHOE TO PROVIDE ALL DAY COMFORT. Comfort Footbed 95 Percent RECYCLED FLEX GROOVES Multiple channels for high flexibility where you need it most. FLEX GROOVES Offer high flexibility in the forefoot. FLEX GROOVES for increased flexibility Full rubber outsole Rubber outsole provides traction and durability Heel TPU cage To provide locked in feel. Lightweight mesh upper A minimal feel and more direct touch from a lightweight mesh upper engineered for high acceleration. This product is made with recycled content as part of our ambition to end plastic waste.'
  },
  {
    id :5,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#1746A2",
    tag: 'new',

  },
  {
    id :6,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#749F82",
  },
  {
    id :7,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#DD5353",
    tag: 'new',
  },
  {
    id :8,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#4C0033",
  },
  {
    id :9,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 1000,
    discount: 20,
    brand: "reebok",
    colorA: "#000",
    colorB: "#FF1E1E",
    colorC: "#367E18",
  }
]