
export const products = [
  {
    id :1,
    name : "Nike AJ 12 retro",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "nike",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#749F82",
    desc: "Available 7/24 at 10:00 AM The OG Air Jordan 12 was a first for Jordan Brand, even if what MJ did wearing them wasn't a first for him. Lacing up in the first official Jordan Brand model throughout the 1996 - 97 season, MJ won another title in the Air Jordan 12, often rocking the OG Cherry colourway. Nearly 25 years later, the beloved Cherry is receiving a classic twist with this new Air Jordan 12 colourway. Instead of University Red dominating the makeup of the outside upper, midsole and sole, the Red Metallic colourway reverses the Cherry original, with a clean white leather covering the upper instead. To top it all off, University Red accents on the midfoot and eyestays complete the full twist."
  },
  {
    id :2,
    name : "Addidas Supernova ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "addidas",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#749F82",

  },
  {
    id :3,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#628E90",
    colorC: "#749F82",
  },
  {
    id :4,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#628E90",
  },
  {
    id :5,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#BCCEF8",
    colorC: "#1746A2",
  },
  {
    id :6,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#749F82",
  },
  {
    id :7,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#DD5353",
  },
  {
    id :8,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#2192FF",
    colorC: "#4C0033",
  },
  {
    id :9,
    name : "Reebok Nanofles TR ",
    img:'/sepatu.png',
    rating: 4.5,
    price: 100000,
    brand: "reebok",
    colorA: "#000",
    colorB: "#FF1E1E",
    colorC: "#367E18",
  }
]