import { yupResolver } from '@hookform/resolvers/yup';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useForm } from 'react-hook-form';
import { alertService, userService } from 'services';
import * as Yup from 'yup';
import style from './Account.module.css';



export default function Register(){
  const router = useRouter();

  // console.log(userService?.userValue)

  const validationSchema = Yup.object().shape({
    email: Yup.string().required('email is required'),
    firstName: Yup.string().required('firstname is required'),
    lastName: Yup.string().required('lastname is required'),
    username: Yup.string().required('username is required'),
    password: Yup.string()
      .required('password is reqired')
      .min(6, 'password must be at least 6 char')
  })
  const formOpt = {resolver: yupResolver(validationSchema)}

  const {register, handleSubmit, formState} = useForm(formOpt)
  const {errors} = formState

  function onSubmit(user){
    return userService.register(user)
      .then(()=>{
        alertService.success('registration successfull',{
          keepAfterRouteChange: true
        }),
        router.push('login')
      })
      .catch(alertService.error)
    }
    
    return(
      <>
        <Head>
          <title>Shoes Shop | Create Account</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
        </Head>
        
        <div className={style.container}>
          <div className={style.wrapper}>
            <Image src={'/signup.svg'} width={500} height={500} objectFit='contain'/>
          </div>
          <div className={style.card}>
            <div className={style.header}>
              <Image className={style.img} src={'/shoesshop.svg'} alt='logo' width={70} height={70}/>
              <div className={style.contentHeader}>
                <h1 className={style.title}>Create Account</h1>
                <p className={style.subTitle}>Find your best shoes with Shoes Shop</p>
              </div>
            </div>
          <div>
            <form className={style.form} onSubmit={handleSubmit(onSubmit)}>
              <div className={style.formGroup}>
                <label>Email</label>
                <input className={style.inpForm} name='email' type='text' {...register('email')}/>
                <small className={style.errorMsg}>{errors.email?.message}</small>
              </div>
              <div className={style.formGroup}>
                <label>First Name</label>
                <input className={style.inpForm} name='firstName' type='text' {...register('firstName')}/>
                <small className={style.errorMsg}>{errors.firstName?.message}</small>
              </div>
              <div className={style.formGroup}>
                <label>Last Name</label>
                <input className={style.inpForm} name='lastName' type='text' {...register('lastName')}/>
                <small className={style.errorMsg}>{errors.lastName?.message}</small>
              </div>
              <div className={style.formGroup}>
                <label>Username</label>
                <input className={style.inpForm} name='username' type='text' {...register('username')}/>
                <small className={style.errorMsg}>{errors.username?.message}</small>
              </div>
              <div className={style.formGroup}>
                <label>Password</label>
                <input className={style.inpForm} name='password' type='password' {...register('password')}/>
                <small className={style.errorMsg}>{errors.password?.message}</small>
              </div>
              <div className={style.container_helper}>
                <p className={style.helper}>Have an account yet ?
                <Link href={'/account/login'}>
                  <span> Log In</span>
                </Link></p>
              </div>
              <button className={style.btn} disabled={formState.isSubmitting}>
                Sign Up
              </button>
            </form>
          </div>
        </div>
      </div>
    </>
  )
}