import Head from "next/head"
import LoginComponent from "../../../components/LoginComponent/LoginComponent"
import Style from './Login.module.css'

function index(){
  return(
    <>
    <Head>
      <title>Shoes Shop | Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" />
    </Head>
    <div className={Style.container}>
      {/* <Image src={'/logo.svg'} layout='fill' alt="img"/> */}
      <div className={Style.content}>
        <LoginComponent/>
        {/* <BtnFilter/> */}
      </div>
    </div>
    </>
  )
}
export default index