import Head from 'next/head'
import React from 'react'
import Layouts from '../../components/Layouts/Layouts'
import PurchaseDetail from '../../components/PurchaseDetail/PurchaseDetail'
import Section from '../../components/Section/Section'
import style from './Checkout.module.css'

export default function index() {
  return (
    <div>
      <Head>
        <title>Shoes Shop | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layouts>
        <Section>
          <div className={style.container}>
            <PurchaseDetail
              item={'addidas supernova'}
              price={"20.000"}
              total={'21.000'}
              name={'nant'}
              adr={'bandung'}
            />
          </div>
        </Section>
      </Layouts>
    </div>
  )
}
