/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Card from '../../components/Card/Card'
import Filter from '../../components/Filter/Filter'
import Layouts from '../../components/Layouts/Layouts'
import Search from '../../components/Search/Search'
import Section from '../../components/Section/Section'
import Select from '../../components/Select/Select'
import style from './Products.module.css'

export default function index({product}) {
  const [data, setData] = useState(product)
  const [dataSearch, setDataSearch] = useState('')
  const [selected, setSelected] = useState('')
  const [openFilter, setOpenFilter] = useState(false)

  const dotPrice =(numb)=>{
    return numb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')
  }
  const priceDisc=(numb, disc)=>{
    const temp = numb/disc
    return parseInt(numb-temp)
    // console.log(temp)
  }

  const onChangeSearch = (e) => {
    // console.log(e.target.value);
    setDataSearch(e.target.value);
  }
  const onSelected = (e) => {
    setSelected(e.target.value);
    // console.log(e.target.value);
  }

  useEffect(()=>{
   if(dataSearch){
    const search = dataSearch.toLowerCase()
    const temp = data.filter((data)=>data.name.toLowerCase().includes(search))
    setData(temp)
   }else{
    setData(product)
   }
  }, [dataSearch])
  useEffect(()=>{
    if(!selected){
      setData(product)
    }else{
      const temp = data.filter(({brand})=> (brand === selected))
      setData(temp)
    }
  }, [selected])
  const handleSearch =()=>{
    if(dataSearch){
      const search = dataSearch.toLowerCase()
      const temp = data.filter((data)=>data.name.toLowerCase().includes(search))
      setData(temp)
      console.log(dataSearch)
    }else{
      setData(product)
    }
  }
  const handleClearSearch =()=>{
    if(dataSearch!= ''){
      setDataSearch('')
      setData(product)
    }
  }

  // useEffect(() => {
  //   if ((selected !== '') && (dataFound !== '')) {
  //     const dataFilter = data
  //       .filter(({ name }) => dataFound ? (name.toLowerCase().includes(dataFound.toLowerCase())) : true)
  //       .filter(({ brand }) => selected ? (brand === selected) : true)
  //     setData(dataFilter)
  //     return
  //   } else if ((selected === '') && (dataFound !== '')) {
  //     const dataFilter = data
  //       .filter(({ name }) => dataFound ? (name.toLowerCase().includes(dataFound.toLowerCase())) : true)
  //     setData(dataFilter)
  //     return
  //   } else if ((selected !== '') && (dataFound === '')) {
  //     const dataFilter = data
  //       .filter(({ brand }) => selected ? (brand === selected) : true)
  //     setData(dataFilter)
  //   }else{
  //     fetchApiAsyncAwait();
  //   }
  // }, [selected, dataFound])

  return (
    <Layouts>
      <Head>
        <title>Shoes Shop | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className={style.container}>
        <Section>
          <div className={style.filter}>
            <Search
              onChangeInput={onChangeSearch}
              value={dataSearch}
              // onSearch={handleSearch}
              onClear={handleClearSearch}
            />
            <Select
              onChangeSelect={onSelected}
              value={selected}
              />
          </div>
          <button className={style.btnFilter} onClick={()=>setOpenFilter(true)}>Filter</button>
          <p className={style.length_products}>{data.length} products</p>
          {!openFilter? ''
            :
            <Filter handleCloseFilter={()=>setOpenFilter(false)}/>
          }
        </Section>
        <Section>
            <div className={style.products}>
              {data.length != 0 && data.map((shoes, i) =>
                // <Link href={`products/${shoes.id}`} key={i} style={{ textDecoration: 'none', color: 'inherit' }}>
                  <Card key={i}
                    idProduct={shoes.id}
                    img={shoes.img}
                    disc={shoes.discount}
                    name={shoes.name}
                    price={dotPrice(shoes.price)}
                    priceAftDisc={dotPrice(priceDisc(shoes.price, shoes.discount))}
                    ratting={shoes.rating}
                    brand={shoes.brand}
                    colorA={shoes.colorA}
                    colorB={shoes.colorB}
                    colorC={shoes.colorC}
                  />
                // </Link>
              )}
            </div>
        </Section>
        </div>
    </Layouts>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/products')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
