/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { FaFilter } from 'react-icons/fa'
import Card from '../../components/Card/Card'
import Filter from '../../components/Filter/Filter'
import Layouts from '../../components/Layouts/Layouts'
import Search from '../../components/Search/Search'
import Section from '../../components/Section/Section'
import Select from '../../components/Select/Select'
import style from './Products.module.css'

export default function index({product}) {
  const [data, setData] = useState(product)
  const [dataSearch, setDataSearch] = useState('')
  const [selected, setSelected] = useState('')
  const [openFilter, setOpenFilter] = useState(false)
  const [checkRating, setCheckRating] = useState('')
  const [hasDiscount, setHasDiscount] = useState(false)

  // console.log([...data])

  const dotPrice =(numb)=>{
    return numb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')
  }
  const priceDisc=(numb, disc)=>{
    const temp = numb/disc
    return parseInt(numb-temp)
    // console.log(temp)
  }
  
  // event handlers
  const handleClearSearch =()=>{
    if(dataSearch!= ''){
      setDataSearch('')
      setData(product)
    }
  }
  const clearFlter = () =>{
    setCheckRating('')
    setData(product)
  }
  const handleRating = (e) =>{
    setCheckRating(e.target.value)
    console.log(e.target.value)
  }
  const onChangeSearch = (e) => {
    // console.log(e.target.value);
    setDataSearch(e.target.value);
  }
  const onSelected = (e) => {
    setSelected(e.target.value);
    // console.log(e.target.value);
  }
  const handleDiscount = (e) => {
    setHasDiscount(e.target.checked);
    console.log(e.target.checked);
  }


  // filter by brand
  const filterBrand = (temp) =>{
    if(!selected){
      return temp
    }
    const filterShoes = temp.filter((shoes)=>(shoes.brand == selected))
    return filterShoes
  }
  //search by name shoes
  const searchShoes = (temp) =>{
    if(!dataSearch){
      return temp
    }
    const searchShoes = dataSearch.toLowerCase()
    const foundShoes = temp.filter((shoes)=>shoes.name.toLowerCase().includes(searchShoes))
    return foundShoes
  }
  // filter by rating
  const filterRating = (temp) => {
    if(!checkRating){
      return temp
    }
    const shoesRating = temp.filter((data)=> data.rating == checkRating)
    return shoesRating
  }
  // filter has discount --not displayed
  const filterDiscount = (temp) =>{
    if(!hasDiscount){
      return temp
    }
    const shoesDiscount = temp.filter((data)=>data.discount)
    console.log(shoesDiscount)
    return (shoesDiscount)
  }

  useEffect(()=>{
    let filterData = filterBrand(product)
    filterData = searchShoes(filterData)
    filterData = filterRating(filterData)
    filterData = filterDiscount(filterData)
    setData(filterData)
  }, [selected, dataSearch, checkRating, hasDiscount])


  return (
    <Layouts>
      <Head>
        <title>Shoes Shop | Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className={style.container}>
        <Section>
          <div className={style.filter}>
            <Search
              onChangeInput={onChangeSearch}
              value={dataSearch}
              // onSearch={handleSearch}
              onClear={handleClearSearch}
            />
            <Select
              onChangeSelect={onSelected}
              value={selected}
              />
          </div>
          <button className={style.btnFilter} onClick={()=>setOpenFilter(true)}><FaFilter/> Filter</button>
          <p className={style.length_products}>display <span>{data.length} products</span> from {product.length} products</p>
          {!openFilter? ''
            :
            <Filter 
              handleCloseFilter={()=>setOpenFilter(false)}
              onRating={handleRating}
              handleClear={clearFlter}
              onDiscount={handleDiscount}
            />
          }
        </Section>
        <Section>
            <div className={style.products}>
              {data.length != 0 && data.map((shoes, i) =>
                // <Link href={`products/${shoes.id}`} key={i} style={{ textDecoration: 'none', color: 'inherit' }}>
                  <Card key={i}
                    idProduct={shoes.id}
                    img={shoes.img}
                    disc={shoes.discount}
                    name={shoes.name}
                    price={dotPrice(shoes.price)}
                    priceAftDisc={dotPrice(priceDisc(shoes.price, shoes.discount))}
                    ratting={shoes.rating}
                    brand={shoes.brand}
                    colorA={shoes.colorA}
                    colorB={shoes.colorB}
                    colorC={shoes.colorC}
                  />
                // </Link>
              )}
            </div>
        </Section>
        </div>
    </Layouts>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/products')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
