/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import CardDetail from '../../../components/CardDetail/CardDetail';
import CardImg from '../../../components/CardImg/CardImg';
import Section from '../../../components/Section/Section';
import style from './Detail.module.css';

export default function Detail({ product, city }) {
  const [data, setData] = useState(product);
  const [dataCity, setDataCity] = useState(city);
  const [size, setSize] = useState();
  const [selectCity, setSelectCity] = useState();
  const [addr, setAddr] = useState();
  const router = useRouter();

  const generateId = (length) => {
    let result = '';
    const char = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    const charLength = char.length;
    for (let i = 0; i < length; i++) {
      result += char.charAt(Math.floor(Math.random() * charLength));
    }
    return `SSHP${result}`;
  };

  const onSubmit = (e) => {
    const userOrder = {
      orderId: generateId(8),
      address: addr,
      city: selectCity,
      size,
    };
    e.preventDefault();
    router.push({
      pathname: `/checkout/${product.id}`,
      query: {
        orderId: userOrder.orderId,
        address: userOrder.address,
        city: userOrder.city,
        size: userOrder.size,
      },
    });
  };

  const dotPrice = (numb) => numb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.');
  const priceDisc = (numb, disc) => {
    const temp = (numb * disc) / 100;
    return parseInt(numb - temp);
  };
  const handleSize = (e) => {
    setSize(e.target.value);
  };
  const handleAddr = (e) => {
    setAddr(e.target.value);
  };
  const handleCity = (e) => {
    setSelectCity(e.target.value)
    // console.log(e.target.value)
  }

  return (
    <>
      <Head>
        <title>
          Shoes Store | Detail Shoes
          {product.id}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Section>
        <div className={style.container}>
          <div className={style.content}>
            <CardImg img={data.img} />
            <CardDetail
              idProduct={data.id}
              image={data.img}
              title={data.name}
              price={dotPrice(data.price)}
              priceAftDisc={dotPrice(priceDisc(data.price, data.discount))}
              rating={data.rating}
              desc={data.desc}
              discount={data.discount}
              sizeData={data.size}
              dataCity={dataCity}
              onSize={handleSize}
              onCity={handleCity}
              btnDisable={!(size && addr)}
              helper={size}
              onInputAddr={handleAddr}
              helperAddr={addr}
              onBtnAction={onSubmit}
            />
          </div>
        </div>
      </Section>
    </>
  );
}
export async function getServerSideProps({ params }) {
  const res1 = await fetch(`https://shoes-shop-green.vercel.app/api/product/`+(params.id));
  const res2 = await fetch(`https://shoes-shop-green.vercel.app/api/city`)
  
  const product = await res1.json();
  const city = await res2.json()
  return {
    props: {
      product,
      city
    },
  };
}
