import Head from 'next/head'
import Image from 'next/image'
import Layouts from '../components/Layouts/Layouts'
import Section from '../components/Section/Section'
import style from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={style.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Section>
          <div className={style.hero}>
            <div className={style.hero__container}>
              <h1 className={style.hero__headline}>Lets Make <br /> Your Day <span className={style.highlight}>Excited</span></h1>
              <p className={style.hero__headlinesupport}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis, lectus magna fringilla urna, porttitor rhoncus dolor purus non enim praesent elementum facilisis leo, vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis.
              </p>
            </div>
            <div className={style.banner}>
              <Image src="/hero_banner.png" width="500" height="470" style={{ marginLeft: 8 + "px" }}/>
            </div>
            
          </div>
        </Section>
      </Layouts>
    </div>
  )
}
