import Head from 'next/head'
import React, { useState } from 'react'
import Layouts from '../../../components/Layouts/Layouts'
import PurchaseDetail from '../../../components/PurchaseDetail/PurchaseDetail'
import Section from '../../../components/Section/Section'
import style from './Checkout.module.css'

export default function index({product}) {
  
  const [data, setData] = useState(product)

  return (
    <div>
      <Head>
        <title>Shoes Shop | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layouts>
        <Section>
          <div className={style.container}>
            <PurchaseDetail
              orderId={'SSHP'+Math.floor(Math.random() * 3000)}
              item={data.name}
              price={data.price}
              brand={data.brand}
              tax={10000}
              total={data.price+10000}
              name={'nant'}
              adr={'bandung'}
              img={data.img}
            />
          </div>
        </Section>
      </Layouts>
    </div>
  )
}
export async function getServerSideProps({params}){
  const res = await fetch('http://localhost:3000/api/product/'+params.id)
  const product = await res.json()
  return {
    props:{
      product
    }
  }
}