import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { userService } from 'services'
import PurchaseDetail from '../../../components/PurchaseDetail/PurchaseDetail'
import Section from '../../../components/Section/Section'
import style from './Checkout.module.css'


export default function index({product}) {
  // console.log(product)
  const [data, setData] = useState(product)
  const router = useRouter()

  console.log(router)
  
  // handle history
  const onSubmitPayment =()=>{
    let temp = {
      email: userService?.userValue.email,
      name: userService?.userValue.firstName,
      size: router.query.size,
      idOrder: router.query.orderId,
      item: data.name,
      price: priceDisc(data.price, data?.discount)+pricePpn(data.price),
      status:'process'
    }
    const dataLocal = localStorage.getItem('history')
    const dataHistory = dataLocal? [...JSON.parse(dataLocal), temp] : [temp]
    if(dataLocal){
      localStorage.removeItem('history')
    }
    localStorage.setItem('history', JSON.stringify(dataHistory))
    console.log(dataHistory)
  }

  const dotPrice =(numb)=>{
    return numb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')
  }
  const priceDisc=(numb, disc)=>{
    let temp = numb/disc
    if(disc == null){
      return numb
    }
    return parseInt(numb-temp)
  }
  const pricePpn = (numb) =>{
    const temp = (numb*0.01)
    return parseInt(temp*10)
  }

  // handle options payment
  const handlePayment =()=>{
    console.log('handle click')
  }
  console.log(priceDisc(data.price, data?.discount)+pricePpn(data.price))

  return (
    <div>
      <Head>
        <title>Shoes Shop | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <>
        <Section>
          <div className={style.container}>
            <PurchaseDetail
              orderId={router.query.orderId}
              idProduct={data.id}
              name={userService?.userValue.firstName.concat(' ',userService?.userValue.lastName)}
              addr={router.query.address}
              size={router.query.size}
              item={data.name}
              brand={data.brand}
              img={data.img}
              tax={dotPrice(pricePpn(data.price))}
              price={dotPrice(data.price)}
              total={dotPrice(priceDisc(data.price, data?.discount)+pricePpn(data.price))}
              discount={dotPrice(priceDisc(data.price, data?.discount))}
              tagDisc={data.discount}
              onOptPayment={handlePayment}
              onPayment={onSubmitPayment}
            />
          </div>
        </Section>
      </>
    </div>
  )
}
export async function getServerSideProps({params}){
  const res = await fetch('http://localhost:3000/api/product/'+params.id)
  const product = await res.json()
  return {
    props:{
      product
    }
  }
}