import Head from 'next/head'
import { FaUser } from 'react-icons/fa'
import { userService } from 'services'
import Section from '../../components/Section/Section'
import { TableHistory } from '../../components/TableHistory/TableHistory'
import style from './History.module.css'

export const historyData = [
  {
    id: 1,
    name: 'nike aj 1',
    price: 10000,
    status: 'pending'
  },
  {
    id: 2,
    name: 'nike aj 1',
    price: 10000,
    status: 'process'
  },
  {
    id: 3,
    name: 'nike aj 1',
    price: 10000,
    status: 'pending'
  },
  {
    id: 4,
    name: 'nike aj 1',
    price: 10000,
    status: 'success'
  },
  {
    id: 5,
    name: 'nike aj 1',
    price: 10000,
    status: 'failed'
  },
  {
    id: 6,
    name: 'nike aj 1',
    price: 10000,
    status: 'failed'
  },
]

export default function index({product}) {
  // console.log(product)
  // const {data : session} = useSession()

  const sumPrice =(data)=>{
    for(var i=0; i<data.length; i++){
      return (data[i].price+data[i+1].price)
    }
  }
  
  return (
    <>
      <Head>
        <title>Shoes Shop | History Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <>
        <div className={style.container}>
          <Section>
            <h1 className={style.title}>History Payment</h1>
            <FaUser className={style.img} size={30}/>
            <div className={style.wrapperContent}>
              <h4 className={style.subtitle}>Summarize</h4>
              <p className={style.text}>User Name: <span> {userService? `${userService?.userValue.username}`: 'hello world'}</span></p>
              <p className={style.text}>Emai: <span> {userService? `${userService?.userValue.email}`: 'helloworld@mail.com'}</span></p>
              <p className={style.text}>Total Spent: <span> Rp. {sumPrice(product)}</span></p>
            </div>
            <div className={style.wrapperTable}>
              <TableHistory dataHistory={historyData}/>
            </div>
          </Section>
        </div>
      </>
    </>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/product')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
