import Head from 'next/head'
import React from 'react'
import Layouts from '../../components/Layouts/Layouts'
import Section from '../../components/Section/Section'
import { TableHistory } from '../../components/TableHistory/TableHistory'
import style from './History.module.css'

export default function index({product}) {
  console.log(product)
  return (
    <>
      <Head>
        <title>Shoes Shop | History Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layouts>
        <div className={style.container}>
          <Section>
            <h1 className={style.title}>History Payment</h1>
            <div className={style.wrapperTable}>
              <TableHistory dataHistory={product}/>
            </div>
          </Section>
        </div>
      </Layouts>
    </>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/product')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
