import { Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { FaUser } from 'react-icons/fa'
import { userService } from 'services'
import Section from '../../components/Section/Section'
import style from './History.module.css'

export default function index({product}) {

  const [data, setData] = useState()

  const getItemLocal =()=>{
    const item = localStorage.getItem('history')
    const parseItem = JSON.parse(item)
    const x = parseItem?.filter((data)=> data.name == userService?.userValue.firstName)
    setData(x)
  }

  useEffect(()=>{
    getItemLocal()
  },[])
  console.log(data)


  const sumPrice =(data)=>{
    if(data){
      let sum=0
      data?.forEach(element => {
        sum+=element.price
      });
      return sum
    }else{
      return 0
    }
  }

  const dotPrice =(numb)=>{
    return numb.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')
  }
  
  return (
    <>
      <Head>
        <title>Shoes Shop | History Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <>
        <div className={style.container}>
          <Section>
            <h1 className={style.title}>History Payment</h1>
            <FaUser className={style.img} size={30}/>
            <div className={style.wrapperContent}>
              <h4 className={style.subtitle}>Summarize</h4>
              <p className={style.text}>User Name: <span> {userService? `${userService?.userValue.username}`: 'hello world'}</span></p>
              <p className={style.text}>Emai: <span> {userService? `${userService?.userValue.email}`: 'helloworld@mail.com'}</span></p>
              <p className={style.text}>Total Spent: <span> Rp. {dotPrice(sumPrice(data))}</span></p>
            </div>
            <div className={style.wrapperTable}>
              <TableContainer component={Paper}>
                <Table sx={{ minWidth: 650 }} aria-label="simple table">
                  <TableHead>
                    <TableRow>
                      <TableCell>No</TableCell>
                      <TableCell align="center">Order ID</TableCell>
                      <TableCell align="left">Item</TableCell>
                      <TableCell align="left">Price</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {data?.map((dataTable, i)=>(
                      <TableRow key={i} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                        <TableCell>{i+1}</TableCell>
                        <TableCell align='center'>{dataTable.idOrder}</TableCell>
                        <TableCell>{dataTable.item}</TableCell>
                        <TableCell>Rp. {dotPrice(dataTable.price)}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </div>
          </Section>
        </div>
      </>
    </>
  )
}
export async function getStaticProps(){
  try{
    const res = await fetch('http://localhost:3000/api/product')
    const product = await res.json()
    return {
      props:{
        product
      }
    }
  }
  catch(err){
    console.error(err)
  }
  return {
    props:{
      product
    }
  }
}
